services:
  midgard-report:
    image: midgard/report:latest
    container_name: midgard-report
    networks:
      - midgard-network
    restart: always
    ports:
      - 10003:8080
    environment:
      - POSTGRES_PRIMARY=midgard-postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_DB=midgard-report
      - ARGINE_URL=http://argine:3000

  midgard-postgres:
    image: postgres:latest
    container_name: midgard-postgres
    networks:
      - midgard-network
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - midgard-pg-data:/var/lib/postgresql/data

volumes:
  midgard-pg-data:
    driver: local

networks:
  midgard-network:
    external: true
    name: argineNetwork
